apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator
      imagePullSecrets:
        - name: k8scc01covidacr-registry-connection
      containers:
        - name: minio-operator
          image: minio/operator:v4.0.11
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 500Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
