apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    istio-injection: enabled
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: minio.example.ca
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio-console
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - host: minio-console.example.ca
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 9090
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  host: "*.minio.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: "ISTIO_MUTUAL"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pods
---
## MinIO Tenant Definition
apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  name: minio
  ## Optionally pass labels to be applied to the statefulset pods
  labels:
    app: minio
  ## Annotations for MinIO Tenant Pods
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
    sidecar.istio.io/inject: "true"
## If a scheduler is specified here, Tenant pods will be dispatched by specified scheduler.
## If not specified, the Tenant pods will be dispatched by default scheduler.
# scheduler:
#  name: my-custom-scheduler
spec:
  ## Registry location and Tag to download MinIO Server image
  image: k8scc01covidacr.azurecr.io/minio/minio:e5044327
  imagePullPolicy: IfNotPresent
  imagePullSecret:
    name: image-pull-secret
  ## Secret with credentials to be used by MinIO Tenant.
  ## Refers to the secret object created above.
  credsSecret:
    name: minio
  ## Specification for MinIO Zone(s) in this Tenant.
  zones:
  - servers: 4 ## Servers specifies the number of MinIO Tenant Pods / Servers in this zone.
    ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
    volumesPerServer: 4
    ## This VolumeClaimTemplate is used across all the volumes provisioned for MinIO Tenant in this
    ## Zone.
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

    ## Used to specify a toleration for a pod
    tolerations:
     - effect: NoSchedule
       key: dedicated
       operator: Equal
       value: storage

    ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
    ## eligible to run on a node, the node must have each of the
    ## indicated key-value pairs as labels.
    ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    nodeSelector:
      agentpool: storagepool1

    ## Affinity settings for MinIO pods. Read more about affinity
    ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: v1.min.io/tenant
                operator: In
                values:
                - instance-name
            topologyKey: kubernetes.io/hostname

    ## Configure resource requests and limits for MinIO containers
    # resources:
    #   requests:
    #     cpu: 250m
    #     memory: 16Gi
    #   limits:
    #     cpu: 500m
    #      memory: 16Gi
    resources:
      requests:
        memory: 20Gi
        cpu: 2
      limits:
        memory: 32Gi
        cpu: 5

  ## Mount path where PV will be mounted inside container(s).
  mountPath: /export
  ## Sub path inside Mount path where MinIO stores data.
  # subPath: /data

  ## Use this field to provide a list of Secrets with external certificates. This can be used to to configure
  ## TLS for MinIO Tenant pods. Create secrets as explained here:
  ## https://github.com/minio/minio/tree/master/docs/tls/kubernetes#2-create-kubernetes-secret
  # externalCertSecret:
  #   - name: tls-ssl-minio
  #     type: kubernetes.io/tls

  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false
  ## Enable S3 specific features such as Bucket DNS which would allow `buckets` to be
  ## accessible as DNS entries of form `<bucketname>.minio.default.svc.cluster.local`
  s3:
    ## This feature is turned off by default
    bucketDNS: false
  ## This field is used only when "requestAutoCert" is set to true. Use this field to set CommonName
  ## for the auto-generated certificate. Internal DNS name for the pod will be used if CommonName is
  ## not provided. DNS name format is *.minio.default.svc.cluster.local
  certConfig:
    commonName: ""
    organizationName: []
    dnsNames: []
  ## PodManagement policy for MinIO Tenant Pods. Can be "OrderedReady" or "Parallel"
  ## Refer https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#pod-management-policy
  ## for details.
  podManagementPolicy: Parallel
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  # env:
  # - name: MINIO_BROWSER
  #   value: "off" # to turn-off browser
  # - name: MINIO_STORAGE_CLASS_STANDARD
  #   value: "EC:2"
  env:
  - name: MINIO_BROWSER
    value: "on"
  - name: MINIO_POLICY_OPA_URL
    value: "http://opa.minio:8181/v1/data/httpapi/authz/allow"
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: XXXXXX
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: https://login.microsoftonline.com/XXXXXX/v2.0/.well-known/openid-configuration
  ## PriorityClassName indicates the Pod priority and hence importance of a Pod relative to other Pods.
  ## This is applied to MinIO pods only.
  ## Refer Kubernetes documentation for details https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass/
  # priorityClassName: high-priority

  ## Define configuration for Console (Graphical user interface for MinIO)
  ## Refer https://github.com/minio/console
  console:
    image: minio/console:v0.4.6
    replicas: 2
    consoleSecret:
      name: console
