apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: docker.elastic.co/logstash/logstash-oss
  newName: docker.elastic.co/logstash/logstash-oss
  newTag: 7.10.2

namespace: minio-operator
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.kubernetes.io/name: logstash
  app.kubernetes.io/instance: minio-audit

resources:
- logstash/serviceaccount.yaml
- logstash/statefulset.yaml
- logstash/service-headless.yaml
- logstash/service.yaml
- logstash/configmap.yaml

secretGenerator:
  - name: minio-audit-logstash
    env: secret.env
