apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configure repo and tag of MinIO Operator Image
images:
  - name: minio/k8s-operator
    newName: minio/k8s-operator
    newTag: v3.0.28

namespace: minio-operator

resources:
  - operator-kustomize/namespace.yaml
  - operator-kustomize/service-account.yaml
  - operator-kustomize/cluster-role.yaml
  - operator-kustomize/cluster-role-binding.yaml
  - operator-kustomize/crds/minio.min.io_tenants.yaml
  - operator-kustomize/service.yaml
  - operator-kustomize/deployment.yaml
